name: 'Terraform CI/CD'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'

permissions:
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-2'

jobs:
  terraform_static_analysis:
    name: 'Terraform Static Analysis'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Format
        working-directory: tf-mods-version  # Set the working directory to the 'terraform' folder
        run: |
          terraform fmt -check
          if [ $? -ne 0 ]; then
            exit 1
          fi

      - name: Terraform Initialize
        working-directory: tf-mods-version  # Set the working directory to the 'terraform' folder
        run: terraform init

      - name: Terraform Validate
        working-directory: tf-mods-version  # Set the working directory to the 'terraform' folder
        run: terraform validate

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version

      - name: Terraform Lint
        working-directory: tf-mods-version  # Set the working directory to the 'terraform' folder
        run: tflint

  terraform_plan_test:
    name: 'Terraform Plan for Test'
    runs-on: ubuntu-latest
    needs: terraform_static_analysis
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Plan for Test
        working-directory: tf-mods-version  # Set the working directory to the 'terraform' folder
        id: plan-test
        run: |
          terraform init
          terraform plan -out=plan-test  # Removed the -var-file argument
          terraform show -no-color plan-test > plan-test.txt
      
      - name: Upload Terraform Plan Artifact for Test
        uses: actions/upload-artifact@v3
        with:
          name: plan-test
          path: terraform/plan-test  # Adjust the path to include the 'terraform' folder

  terraform_apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: [terraform_plan_test]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirmation == 'yes'
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Apply
        working-directory: tf-mods-version  # Set the working directory to the 'terraform' folder
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-2'
          
  # test_deployment:
  #   name: 'Test Deployment'
  #   runs-on: ubuntu-latest
  #   needs: [terraform_apply]
  #   steps:
  #     - name: Wait for DNS propagation
  #       run: sleep 60  # Wait for 60 seconds to allow for DNS propagation

  #     - name: Test HTTPS endpoint
  #       run: |
  #         response=$(curl -s -o /dev/null -w "%{http_code}" https://tm.lab.moabukar.co.uk/workspaces/default/dashboard)
  #         if [ $response -eq 200 ]; then
  #           echo "Deployment successful! Received HTTP 200 OK."
  #         else
  #           echo "Deployment may have issues. Received HTTP $response"
  #           exit 1
  #         fi
