name: Deploy to Amazon ECS Fargate

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2                 # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: app           # set this to your Amazon ECR repository name
  ECS_SERVICE: service               # set this to your Amazon ECS service name
  ECS_CLUSTER: TERRAFORM_CLUSTER                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: ECS_TASK_DEFINITION_APP # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: app          # set this to the name of the container in the
                                               # containerDefinitions section of your task definition
  environment: us-south-west
  
permissions:
  contents: read

jobs:
   terraform:
    name: 'Terraform'
    runs-on: self-hosted
   
    defaults:
      run:
        working-directory: ./
      
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform workflow
        working-directory: ./        
        run: 
          terraform init 
          terraform workplace new ${{ env.environment }} 
          terraform workplace select ${{ env.environment }} 
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.ref == 'refs/heads/feature' && github.event_name == 'push'
        run: terraform apply -auto-approve  
